### ISSUE TITLE
"Pin option" in preferences is behaving weird

### ISSUE THREAD

**Issue by martinengelke** [brainchest/FileFillet-Feedback#4]
I cannot click the option "Pin" before I checked "Show panel at launch", which could be intended as that? 
But then it goes weird. 

If I uncheck "Show panel at launch" the "Pin" option stays checked, but grayed out.

**Comment by sarensw** [comment]
Yes. That's intended. The question is, do you want to pin the window after launch? Pin by default is off and is not saved when you close the app. So if "Show panel at launch" is activated, only then the "Pin" option is taken into account when you restart the system and FileFillet launches. 

And if you turn off "Show panel at launch", then the "Pin" option stays the previous value, so you don't have to tick it again when you reenable "Show Panel at launch"
